# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(verbose_name='\u6d3b\u52a8\u65e5\u671f')),
                ('place', models.CharField(max_length=45, null=True, verbose_name='\u6d3b\u52a8\u5730\u70b9')),
            ],
            options={
                'db_table': 'activity',
            },
        ),
        migrations.CreateModel(
            name='CaseHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=32, verbose_name='\u673a\u4e3b')),
                ('contact', models.CharField(max_length=32, verbose_name='\u624b\u673a\u53f7')),
                ('computer_model', models.CharField(max_length=128, verbose_name='\u7535\u8111\u578b\u53f7')),
                ('problem', models.TextField(max_length=512, verbose_name='\u95ee\u9898\u63cf\u8ff0')),
                ('solution', models.TextField(max_length=1024, verbose_name='\u89e3\u51b3\u529e\u6cd5')),
                ('status', models.IntegerField(choices=[(0, '\u672a\u77e5'), (1, '\u5f85\u7ef4\u4fee'), (2, '\u6b63\u5728\u7ef4\u4fee'), (3, '\u5df2\u7ef4\u4fee')], default=0, verbose_name='\u75c5\u4f8b\u5355\u72b6\u6001')),
                ('volunteer', models.TextField(max_length=512, verbose_name='\u5fd7\u613f\u8005')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genius.Activity')),
            ],
            options={
                'db_table': 'case_history',
            },
        ),
    ]
