# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genius', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casehistory',
            name='solution',
            field=models.TextField(blank=True, max_length=1024, verbose_name='\u89e3\u51b3\u529e\u6cd5'),
        ),
        migrations.AlterField(
            model_name='casehistory',
            name='status',
            field=models.IntegerField(choices=[(0, '\u672a\u77e5'), (1, '\u5f85\u7ef4\u4fee'), (2, '\u6b63\u5728\u7ef4\u4fee'), (3, '\u5df2\u7ef4\u4fee')], default=1, verbose_name='\u75c5\u4f8b\u5355\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='casehistory',
            name='volunteer',
            field=models.TextField(blank=True, max_length=512, verbose_name='\u5fd7\u613f\u8005'),
        ),
    ]
