# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genius', '0004_auto_20160414_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='place',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
